import type { Frame } from "@/types/frame";

export const frames: Frame[] = [
  {
    id: 1,
    slug: "urban-acetate",
    name: "Urban Acetate",
    category: "Moderna",
    material: "Acetato",
    color: "Negro",
    image: "/products-hero.png",
    authority: "DEMO",
  },
  {
    id: 2,
    slug: "titanium-air",
    name: "Titanium Air",
    category: "Premium",
    material: "Titanio",
    color: "Plata",
    image: "/full-catalog.png",
    authority: "DEMO",
  },
  {
    id: 3,
    slug: "crystal-vision",
    name: "Crystal Vision",
    category: "Moderna",
    material: "Acetato",
    color: "Transparente",
    image: "/products-hero.png",
    authority: "DEMO",
  },
  {
    id: 4,
    slug: "vintage-tortoise",
    name: "Vintage Tortoise",
    category: "Clásica",
    material: "Acetato",
    color: "Carey",
    image: "/full-catalog.png",
    authority: "DEMO",
  },
  {
    id: 5,
    slug: "solar-try-on",
    name: "Solar Try On",
    category: "Solar",
    material: "Acetato",
    color: "Negro",
    image: "/glasses.png",
    tryOnImage: "/glasses.png",
    authority: "DEMO",
  },
  {
    id: 6,
    slug: "solar-classic",
    name: "Solar Classic",
    category: "Solar",
    material: "Titanio",
    color: "Negro",
    image: "/sunglasses.png",
    tryOnImage: "/sunglasses.png",
    authority: "DEMO",
  },
  {
    id: 7,
    slug: "circle-special",
    name: "Circle Special",
    category: "Especial",
    material: "Titanio",
    color: "Marrón",
    image: "/img1.png",
    tryOnImage: "/img1.png",
    authority: "DEMO",
  },
  {
    id: 8,
    slug: "solar-color",
    name: "Solar Color",
    category: "Especial",
    material: "Acetato",
    color: "Mixto",
    image: "/sunglasses1.png",
    tryOnImage: "/sunglasses1.png",
    authority: "DEMO",
  },
];

export const featuredFrames = frames.slice(0, 4);
export const tryOnFrames = frames.filter((frame) => Boolean(frame.tryOnImage));
