import type { Frame } from "@/types/frame";

export const frames: Frame[] = [
  {
    id: 1,
    slug: "urban-acetate",
    name: "Urban Acetate",
    category: "Moderna",
    material: "Acetato",
    color: "Negro",
    image: "/frames/urban-acetate.webp",
    tryOnImage: "/frames/urban-acetate.webp",
    authority: "REFERENCE",
  },
  {
    id: 2,
    slug: "titanium-air",
    name: "Titanium Air",
    category: "Premium",
    material: "Titanio",
    color: "Plata",
    image: "/frames/titanium-air.webp",
    tryOnImage: "/frames/titanium-air.webp",
    authority: "REFERENCE",
  },
  {
    id: 3,
    slug: "crystal-vision",
    name: "Crystal Vision",
    category: "Moderna",
    material: "Acetato",
    color: "Transparente",
    image: "/frames/crystal-vision.webp",
    tryOnImage: "/frames/crystal-vision.webp",
    authority: "REFERENCE",
  },
  {
    id: 4,
    slug: "vintage-tortoise",
    name: "Vintage Tortoise",
    category: "Clásica",
    material: "Acetato",
    color: "Carey",
    image: "/frames/vintage-tortoise.webp",
    tryOnImage: "/frames/vintage-tortoise.webp",
    authority: "REFERENCE",
  },
  {
    id: 5,
    slug: "solar-noir",
    name: "Solar Noir",
    category: "Solar",
    material: "Acetato",
    color: "Negro",
    image: "/frames/solar-noir.webp",
    tryOnImage: "/frames/solar-noir.webp",
    authority: "REFERENCE",
  },
  {
    id: 6,
    slug: "solar-aviator",
    name: "Solar Aviator",
    category: "Solar",
    material: "Titanio",
    color: "Plata",
    image: "/frames/solar-aviator.webp",
    tryOnImage: "/frames/solar-aviator.webp",
    authority: "REFERENCE",
  },
  {
    id: 7,
    slug: "circle-brown",
    name: "Circle Brown",
    category: "Especial",
    material: "Titanio",
    color: "Marrón",
    image: "/frames/circle-brown.webp",
    tryOnImage: "/frames/circle-brown.webp",
    authority: "REFERENCE",
  },
  {
    id: 8,
    slug: "solar-color",
    name: "Solar Color",
    category: "Especial",
    material: "Acetato",
    color: "Mixto",
    image: "/frames/solar-color.webp",
    tryOnImage: "/frames/solar-color.webp",
    authority: "REFERENCE",
  },
];

export const featuredFrames = frames.slice(0, 4);
export const tryOnFrames = frames.filter((frame) => Boolean(frame.tryOnImage));
